import type { Metadata } from "next";
import Link from "next/link";
import "../globals.css";

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <section className="h-auto flex flex-col bg-background-neo bg-linear-to-b from-background-neo to-accent-soft-neo font-playfairDisplay">
        <div className=" ">{children}</div>
      </section>
    </>
  );
}

export const metadata: Metadata = {
  title: "Isaac Edwards Blog Page",
  description: "Generated by create next app",
};
