import type { Metadata } from "next";
import Link from "next/link";
import "../globals.css";

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <section className="h-auto flex flex-col bg-Banana-Mania bg-linear-to-b from-Banana-Mania to-Tan font-cormorantGarmond">
        <div className=" ">{children}</div>
      </section>
      <div>
        <nav className="fixed bottom-4 left-1/2 transform -translate-x-1/2 p-4 opacity-80 bg-gray-800 rounded-full shadow-2xl z-50 hidden md:block">
          <div className="flex space-x-4">
            <Link href={"/"} className="text-white hover:text-gray-300">
              Home
            </Link>
            <Link
              href={"/portfolio"}
              className="text-white hover:text-gray-300"
            >
              Portfolio
            </Link>
          </div>
        </nav>
      </div>
    </>
  );
}

export const metadata: Metadata = {
  title: "Isaac Edwards Blog Page",
  description: "Generated by create next app",
};
