import type { Metadata } from "next";
import "../globals.css";
import Background from "@/components/Background";
import { MouseContextProvider } from "@/components/MouseContext";
import DualCirclesBG from "@/components/DualCirclesBG";

export const metadata: Metadata = {
  title: "Isaac Edwards Portfolio Page",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative isolate bg-background-neo min-h-screen"> 
      <DualCirclesBG />
       {children}
    </div>   
  );
}
