import type { Metadata } from "next";
import "../globals.css";
import Background from "@/components/Background";
import { MouseContextProvider } from "@/components/MouseContext";

export const metadata: Metadata = {
  title: "Isaac Edwards Portfolio Page",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <MouseContextProvider>
        <Background>{children}</Background>
      </MouseContextProvider>
    </section>
  );
}
